ALTER TABLE documents ADD COLUMN IF NOT EXISTS last_edited_by UUID REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE documents ADD COLUMN IF NOT EXISTS created_via TEXT;
ALTER TABLE documents ADD COLUMN IF NOT EXISTS last_edited_via TEXT;
